### ISSUE TITLE
Two questions about the implementation of the model

### ISSUE THREAD

**Issue by emmmmmmmmmmmmmmmmmmmmm** [WilliamCCHuang/GraphLIME#12]
Hello! I have two questions about the implementation of the model.
1. I noticed in the graphlime implementation, there is one line of code, `solver.fit(K_bar * n, L_bar * n)`. Why there is `n` in it? It seems different from the paper.
2. I find in your given example, the greedy algorithm performs better than graphlime. The orange line is the result of greedy algorithm.
![image](https://github.com/WilliamCCHuang/GraphLIME/assets/112478376/285dfd17-ceda-4bfa-90d5-638b26029644)

I would appreciate it if you could answer my questions!

**Comment by WilliamCCHuang** [comment]
@emmmmmmmmmmmmmmmmmmmmm Thanks for your question.

1. Compare the optimization objective for Lasso from the [sklearn](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LassoLars.html) document:
$\mathcal{L} = \frac{1}{2 m} ||\vec{y} - X\vec{w}||^2_2 + \alpha ||\vec{w}||_1$,
and that from the paper:
$\mathcal{L} = \frac{1}{2} ||\bar{L} - \sum_k \beta_k \bar{K}^{(k)}||^2_F + \rho ||\vec{\beta}||_1$,
where $m$ is the number of sample and $m=n^2$ here. Then we can conclude that
$\vec{y} = n \bar{L}, X = n \bar{K}$

2. I have checked that  there is no figure like yours in the newest version.

**Comment by emmmmmmmmmmmmmmmmmmmmm** [comment]
I understand that. Thanks a lot for your reply!
