### ISSUE TITLE
Does GraphLIME work for graph classification?

### ISSUE THREAD

**Issue by ZhaoxiangSimonCai** [WilliamCCHuang/GraphLIME#3]
Hi @WilliamCCHuang , thank you for your great work and I'm really interested in using it for my project. I believe the current code is for node classification tasks. Do you plan to add support for graph classification/regression problem in the near future for GraphLIME? Thanks

**Comment by WilliamCCHuang** [comment]
Hi @Olimon660, thanks for your suggestion. According to the paper ["GraphLIME:Local Interpretable Model Explanations for Graph Neural Networks"](https://arxiv.org/pdf/2001.06216.pdf), the current GraphLIME can only support node classification tasks. It does not support graph tasks. However, node regression is possible. I will try to do some experiments for it.
