### ISSUE TITLE
Input data to graphlime 

### ISSUE THREAD

**Issue by abhigoku10** [WilliamCCHuang/GraphLIME#5]
@WilliamCCHuang  hi thanks for opensourcing working just had few queries 
1. since your reading data using pytorch geometric "Planetoid(path, dataset, transform=T.NormalizeFeatures())" and passing data.x and data.edge_attr  if am using default data loading then then 'x = feature of cora'  and 'edge_attr= adjacency matrix' ??

**Comment by WilliamCCHuang** [comment]
@abhigoku10 `data.x` is the node features of graph. However, `GraphLIME` only accept node features `data.x` and adjacency matrix `data.edge_index` as inputs, rather than `data.edge_attr`.
